/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EntropyEncryptMultipleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "confidentialProtocolId"
      | "encryptAndStore"
      | "encryptAndStoreBatch"
      | "encryptAndStoreBatchWithEntropy"
      | "encryptAndStoreWithEntropy"
      | "entropyOracle"
      | "entropyRequests"
      | "getEncryptedValue"
      | "getEntropyOracle"
      | "getTotalValues"
      | "isInitialized"
      | "isKeyInitialized"
      | "requestEntropy"
      | "totalValues"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "EntropyRequested"
      | "ValueEncrypted"
      | "ValueEncryptedWithEntropy"
      | "ValuesEncryptedBatch"
      | "ValuesEncryptedBatchWithEntropy"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "encryptAndStore",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "encryptAndStoreBatch",
    values: [BigNumberish[], BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "encryptAndStoreBatchWithEntropy",
    values: [BigNumberish[], BytesLike[], BytesLike[], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "encryptAndStoreWithEntropy",
    values: [BigNumberish, BytesLike, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "entropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "entropyRequests",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedValue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEntropyOracle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalValues",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isInitialized",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isKeyInitialized",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "requestEntropy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalValues",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptAndStore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptAndStoreBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptAndStoreBatchWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptAndStoreWithEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "entropyRequests",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntropyOracle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalValues",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isKeyInitialized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestEntropy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalValues",
    data: BytesLike
  ): Result;
}

export namespace EntropyRequestedEvent {
  export type InputTuple = [requestId: BigNumberish, caller: AddressLike];
  export type OutputTuple = [requestId: bigint, caller: string];
  export interface OutputObject {
    requestId: bigint;
    caller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueEncryptedEvent {
  export type InputTuple = [key: BigNumberish, user: AddressLike];
  export type OutputTuple = [key: bigint, user: string];
  export interface OutputObject {
    key: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValueEncryptedWithEntropyEvent {
  export type InputTuple = [
    key: BigNumberish,
    requestId: BigNumberish,
    user: AddressLike
  ];
  export type OutputTuple = [key: bigint, requestId: bigint, user: string];
  export interface OutputObject {
    key: bigint;
    requestId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValuesEncryptedBatchEvent {
  export type InputTuple = [keys: BigNumberish[], user: AddressLike];
  export type OutputTuple = [keys: bigint[], user: string];
  export interface OutputObject {
    keys: bigint[];
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValuesEncryptedBatchWithEntropyEvent {
  export type InputTuple = [
    keys: BigNumberish[],
    requestId: BigNumberish,
    user: AddressLike
  ];
  export type OutputTuple = [keys: bigint[], requestId: bigint, user: string];
  export interface OutputObject {
    keys: bigint[];
    requestId: bigint;
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EntropyEncryptMultiple extends BaseContract {
  connect(runner?: ContractRunner | null): EntropyEncryptMultiple;
  waitForDeployment(): Promise<this>;

  interface: EntropyEncryptMultipleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  encryptAndStore: TypedContractMethod<
    [key: BigNumberish, encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  encryptAndStoreBatch: TypedContractMethod<
    [
      keys: BigNumberish[],
      encryptedInputs: BytesLike[],
      inputProofs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  encryptAndStoreBatchWithEntropy: TypedContractMethod<
    [
      keys: BigNumberish[],
      encryptedInputs: BytesLike[],
      inputProofs: BytesLike[],
      requestId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  encryptAndStoreWithEntropy: TypedContractMethod<
    [
      key: BigNumberish,
      encryptedInput: BytesLike,
      inputProof: BytesLike,
      requestId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  entropyOracle: TypedContractMethod<[], [string], "view">;

  entropyRequests: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  getEncryptedValue: TypedContractMethod<[key: BigNumberish], [string], "view">;

  getEntropyOracle: TypedContractMethod<[], [string], "view">;

  getTotalValues: TypedContractMethod<[], [bigint], "view">;

  isInitialized: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  isKeyInitialized: TypedContractMethod<[key: BigNumberish], [boolean], "view">;

  requestEntropy: TypedContractMethod<[tag: BytesLike], [bigint], "payable">;

  totalValues: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "encryptAndStore"
  ): TypedContractMethod<
    [key: BigNumberish, encryptedInput: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "encryptAndStoreBatch"
  ): TypedContractMethod<
    [
      keys: BigNumberish[],
      encryptedInputs: BytesLike[],
      inputProofs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "encryptAndStoreBatchWithEntropy"
  ): TypedContractMethod<
    [
      keys: BigNumberish[],
      encryptedInputs: BytesLike[],
      inputProofs: BytesLike[],
      requestId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "encryptAndStoreWithEntropy"
  ): TypedContractMethod<
    [
      key: BigNumberish,
      encryptedInput: BytesLike,
      inputProof: BytesLike,
      requestId: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "entropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "entropyRequests"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "getEncryptedValue"
  ): TypedContractMethod<[key: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEntropyOracle"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalValues"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isInitialized"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isKeyInitialized"
  ): TypedContractMethod<[key: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "requestEntropy"
  ): TypedContractMethod<[tag: BytesLike], [bigint], "payable">;
  getFunction(
    nameOrSignature: "totalValues"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "EntropyRequested"
  ): TypedContractEvent<
    EntropyRequestedEvent.InputTuple,
    EntropyRequestedEvent.OutputTuple,
    EntropyRequestedEvent.OutputObject
  >;
  getEvent(
    key: "ValueEncrypted"
  ): TypedContractEvent<
    ValueEncryptedEvent.InputTuple,
    ValueEncryptedEvent.OutputTuple,
    ValueEncryptedEvent.OutputObject
  >;
  getEvent(
    key: "ValueEncryptedWithEntropy"
  ): TypedContractEvent<
    ValueEncryptedWithEntropyEvent.InputTuple,
    ValueEncryptedWithEntropyEvent.OutputTuple,
    ValueEncryptedWithEntropyEvent.OutputObject
  >;
  getEvent(
    key: "ValuesEncryptedBatch"
  ): TypedContractEvent<
    ValuesEncryptedBatchEvent.InputTuple,
    ValuesEncryptedBatchEvent.OutputTuple,
    ValuesEncryptedBatchEvent.OutputObject
  >;
  getEvent(
    key: "ValuesEncryptedBatchWithEntropy"
  ): TypedContractEvent<
    ValuesEncryptedBatchWithEntropyEvent.InputTuple,
    ValuesEncryptedBatchWithEntropyEvent.OutputTuple,
    ValuesEncryptedBatchWithEntropyEvent.OutputObject
  >;

  filters: {
    "EntropyRequested(uint256,address)": TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;
    EntropyRequested: TypedContractEvent<
      EntropyRequestedEvent.InputTuple,
      EntropyRequestedEvent.OutputTuple,
      EntropyRequestedEvent.OutputObject
    >;

    "ValueEncrypted(uint256,address)": TypedContractEvent<
      ValueEncryptedEvent.InputTuple,
      ValueEncryptedEvent.OutputTuple,
      ValueEncryptedEvent.OutputObject
    >;
    ValueEncrypted: TypedContractEvent<
      ValueEncryptedEvent.InputTuple,
      ValueEncryptedEvent.OutputTuple,
      ValueEncryptedEvent.OutputObject
    >;

    "ValueEncryptedWithEntropy(uint256,uint256,address)": TypedContractEvent<
      ValueEncryptedWithEntropyEvent.InputTuple,
      ValueEncryptedWithEntropyEvent.OutputTuple,
      ValueEncryptedWithEntropyEvent.OutputObject
    >;
    ValueEncryptedWithEntropy: TypedContractEvent<
      ValueEncryptedWithEntropyEvent.InputTuple,
      ValueEncryptedWithEntropyEvent.OutputTuple,
      ValueEncryptedWithEntropyEvent.OutputObject
    >;

    "ValuesEncryptedBatch(uint256[],address)": TypedContractEvent<
      ValuesEncryptedBatchEvent.InputTuple,
      ValuesEncryptedBatchEvent.OutputTuple,
      ValuesEncryptedBatchEvent.OutputObject
    >;
    ValuesEncryptedBatch: TypedContractEvent<
      ValuesEncryptedBatchEvent.InputTuple,
      ValuesEncryptedBatchEvent.OutputTuple,
      ValuesEncryptedBatchEvent.OutputObject
    >;

    "ValuesEncryptedBatchWithEntropy(uint256[],uint256,address)": TypedContractEvent<
      ValuesEncryptedBatchWithEntropyEvent.InputTuple,
      ValuesEncryptedBatchWithEntropyEvent.OutputTuple,
      ValuesEncryptedBatchWithEntropyEvent.OutputObject
    >;
    ValuesEncryptedBatchWithEntropy: TypedContractEvent<
      ValuesEncryptedBatchWithEntropyEvent.InputTuple,
      ValuesEncryptedBatchWithEntropyEvent.OutputTuple,
      ValuesEncryptedBatchWithEntropyEvent.OutputObject
    >;
  };
}
